name: Nicky
main: io.loyloy.nicky.Nicky
version: 0.7
description: Simple SQL nickname plugin.
author: Melonking
depend: [Vault]

commands:
   nicky:
      description: Nicky Help
      usage: /<command>
   nick:
      description: Set a nickname
      usage: /<command>
   delnick:
      description: Unset a nickname
      usage: /<command>
   realname:
      description: See the owner of a nickname
      usage: /<command>
      aliases:
      - rn

permissions:
    nicky.help:
        default: true
    nicky.set:
        default: op
    nicky.set.other:
        default: op
    nicky.del:
        default: op
    nicky.del.other:
        default: op
    nicky.noblacklist:
        default: op
    nicky.realname:
        default: op
    nicky.color:
        default: op
        children:
            "nicky.color.normal": true
            "nicky.color.extra": true
    nicky.color.normal:
        default: op
        children:
            "nicky.color.0": true
            "nicky.color.1": true
            "nicky.color.2": true
            "nicky.color.3": true
            "nicky.color.4": true
            "nicky.color.5": true
            "nicky.color.6": true
            "nicky.color.7": true
            "nicky.color.8": true
            "nicky.color.9": true
            "nicky.color.a": true
            "nicky.color.b": true
            "nicky.color.c": true
            "nicky.color.d": true
            "nicky.color.e": true
            "nicky.color.f": true
    nicky.color.extra:
        default: op
        children:
            "nicky.color.l": true
            "nicky.color.n": true
            "nicky.color.o": true
            "nicky.color.k": true
            "nicky.color.m": true
            "nicky.color.r": true
    nicky.reload:
        default: op